def get_star_players():
    return ['Chris Gatling',
            'Tom Gugliotta',
            'Christian Laettner',
            'Eddie Jones',
            'Kevin Garnett',
            'Chris Webber',
            'Steve Smith',
            'Rik Smits',
            'Nick Van Exel',
            'Jayson Williams',
            'Tim Duncan',
            'Kobe Bryant',
            'Antoine Walker',
            'Dale Davis',
            'Michael Finley',
            'Allan Houston',
            'Glenn Robinson',
            'Jerry Stackhouse',
            'Rasheed Wallace',
            'Ray Allen',
            'Vince Carter',
            'Allen Iverson',
            'Antonio Davis',
            'Vlade Divac',
            'Anthony Mason',
            'Antonio McDyess',
            'Theo Ratliff',
            'Tracy McGrady',
            'Stephon Marbury',
            'Shareef Abdur-Rahim',
            'Wally Szczerbiak',
            'Steve Nash',
            'Steve Francis',
            'Peja Stojakovic',
            'Paul Pierce',
            "Jermaine O'Neal",
            'Dirk Nowitzki',
            'Baron Davis',
            'Elton Brand',
            'Jamal Mashburn',
            'Brad Miller',
            'Ben Wallace',
            'Yao Ming',
            'Zydrunas Ilgauskas',
            'Shawn Marion',
            'Sam Cassell',
            'Andrei Kirilenko',
            'Jamaal Magloire',
            'Kenyon Martin',
            'Michael Redd',
            'Metta World Peace',
            'Gilbert Arenas',
            'Dwyane Wade',
            'LeBron James',
            "Amar'e Stoudemire",
            'Antawn Jamison',
            'Rashard Lewis',
            'Manu Ginobili',
            'Tony Parker',
            'Richard Hamilton',
            'Chauncey Billups',
            'Chris Bosh',
            'Pau Gasol',
            'Josh Howard',
            'Mehmet Okur',
            'Carlos Boozer',
            'Caron Butler',
            'Carmelo Anthony',
            'Joe Johnson',
            'Dwight Howard',
            'David West',
            'Brandon Roy',
            'Chris Paul',
            'Danny Granger',
            'Devin Harris',
            'Jameer Nelson',
            'Mo Williams',
            'Chris Kaman',
            'Gerald Wallace',
            'Al Horford',
            'Derrick Rose',
            'Deron Williams',
            'Rajon Rondo',
            'Kevin Durant',
            'David Lee',
            'Zach Randolph',
            'Kevin Love',
            'Russell Westbrook',
            'Blake Griffin',
            'Andrew Bynum',
            'Andre Iguodala',
            'Luol Deng',
            'LaMarcus Aldridge',
            'Roy Hibbert',
            'Marc Gasol',
            'Tyson Chandler',
            'Brook Lopez',
            'Joakim Noah',
            'Paul George',
            'Kyrie Irving',
            'James Harden',
            'Jrue Holiday',
            'Damian Lillard',
            'Paul Millsap',
            'John Wall',
            'Stephen Curry',
            'Anthony Davis',
            'DeMar DeRozan',
            'Kyle Korver',
            'Jeff Teague',
            'DeMarcus Cousins',
            'Jimmy Butler',
            'Klay Thompson',
            'Kyle Lowry',
            'Isaiah Thomas',
            'Kawhi Leonard',
            'Draymond Green',
            'Andre Drummond',
            'Gordon Hayward',
            'DeAndre Jordan',
            'Kemba Walker',
            'Giannis Antetokounmpo',
            'Goran Dragic',
            'Kristaps Porziņgis',
            'Victor Oladipo',
            'Bradley Beal',
            'Karl-Anthony Towns',
            'Joel Embiid',
            "D'Angelo Russell",
            'Khris Middleton',
            'Ben Simmons',
            'Nikola Jokic',
            'Nikola Vucevic',
            'Brandon Ingram',
            'Domantas Sabonis',
            'Rudy Gobert',
            'Devin Booker',
            'Luka Doncic',
            'Donovan Mitchell',
            'Jayson Tatum',
            'Trae Young',
            'Pascal Siakam',
            'Bam Adebayo',
            'Mike Conley',
            'Zach LaVine',
            'Zion Williamson',
            'Jaylen Brown',
            'Julius Randle',
            'Jarrett Allen',
            'LaMelo Ball',
            'Darius Garland',
            'Dejounte Murray',
            'Fred VanVleet',
            'Andrew Wiggins',
            'Ja Morant',
            "De'Aaron Fox",
            'Jaren Jackson Jr.',
            'Lauri Markkanen',
            'Anthony Edwards',
            'Shai Gilgeous-Alexander',
            'Tyrese Haliburton',
            'Paolo Banchero',
            'Scottie Barnes',
            'Jalen Brunson',
            'Tyrese Maxey']


def get_training_columns():
      return  [
                'display_first_last',
                'classification',
                'GP',
                'Min_per',
                'Ortg',
                'usg',
                'eFG',
                'TS_per',
                'ORB_per',
                'DRB_per',
                'AST_per',
                'TO_per',
                'FTM',
                'FTA',
                'FT_per',
                'twoPM',
                'twoPA',
                'twoP_per',
                'TPM',
                'TPA',
                'TP_per',
                'blk_per',
                'stl_per',
                'ftr',
                'yr',
                'porpag',
                'adjoe',
                'pfr',
                'ast/tov',
                'drtg',
                'adrtg',
                'dporpag',
                'stops',
                'bpm',
                'obpm',
                'dbpm',
                'gbpm',
                'mp',
                'ogbpm',
                'dgbpm',
                'oreb',
                'dreb',
                'treb',
                'ast',
                'stl',
                'blk',
                'pts',
                'height_wo_shoes',
                'height_w_shoes',
                'weight',
                'wingspan',
                'standing_reach',
                'body_fat_pct',
        ]